---
- name: Install kibana repository
  copy: src=kibana.repo dest=/etc/yum.repos.d/kibana.repo
  tags:
  - packages
  - kibana

- name: Install kibana
  yum: pkg=kibana state=present
  tags:
  - packages
  - kibana

- name: Enable and start kibana
  service: name=kibana enabled=yes state=started
  tags:
  - services
  - kibana
