---
- name: Install kibana repository
  copy: src=kibana.repo dest=/etc/yum.repos.d/kibana.repo
  tags:
  - packages
  - kibana

- name: Install kibana
  yum: pkg=kibana state=present
  tags:
  - packages
  - kibana

- name: Create /etc/kibana/tls
  file: dest=/etc/kibana/tls state=directory owner=kibana group=kibana
        mode=0700
  tags:
  - kibana

# openssl req -new -x509 -sha256 -batch -nodes -newkey rsa:4096 -keyout /etc/kibana/tls/private.pem -subj "/CN=sampoong.wuvt.vt.edu" -days 3650 -out /etc/kibana/tls/public.pem -extensions SAN -config <(cat /etc/pki/tls/openssl.cnf <(printf "[SAN]\nbasicConstraints=critical,CA:true,pathlen:0\nkeyUsage=digitalSignature,keyEncipherment,keyCertSign\nsubjectAltName=DNS:sampoong.wuvt.vt.edu,IP:192.168.0.223"))

- name: Set kibana to only bind on localhost
  lineinfile: "dest=/opt/kibana/config/kibana.yml
              line='server.host: \"127.0.0.1\"' state=present"
  tags:
  - kibana

- name: Enable and start kibana
  service: name=kibana enabled=yes state=started
  tags:
  - services
  - kibana

- name: Install /etc/nginx/sites-available/kibana
  template: src=kibana.nginx.conf.j2 dest=/etc/nginx/sites-available/kibana
  notify: Reload nginx
  tags:
  - nginx

- name: Install nginx sites-enabled link for kibana
  file: dest=/etc/nginx/sites-enabled/kibana
        src=../sites-available/kibana state=link
  notify: Reload nginx
  tags:
  - nginx
