---
- name: Install logstash repository
  copy: src=logstash/logstash.repo dest=/etc/yum.repos.d/logstash.repo
  tags:
  - packages
  - logstash

- name: Install logstash
  yum: pkg=logstash state=present
  tags:
  - packages
  - logstash

- name: Install /etc/logstash/logstash.conf
  copy: src=logstash/logstash.conf dest=/etc/logstash/logstash.conf
  notify: restart logstash
  tags:
  - logstash

- name: Create /etc/logstash/patterns subdirectories
  file: dest=/etc/logstash/patterns state=directory
  tags:
  - logstash

- name: Create /etc/logstash/tls
  file: dest=/etc/logstash/tls state=directory owner=logstash group=logstash
        mode=0700
  tags:
  - logstash

# openssl req -new -x509 -sha256 -batch -nodes -newkey rsa:4096 -keyout /etc/logstash/tls/private.pem -subj "/CN=sampoong.wuvt.vt.edu" -days 3650 -out /etc/logstash/tls/public.pem -extensions SAN -config <(cat /etc/pki/tls/openssl.cnf <(printf "[SAN]\nbasicConstraints=critical,CA:true,pathlen:0\nkeyUsage=digitalSignature,keyEncipherment,keyCertSign\nsubjectAltName=DNS:sampoong.wuvt.vt.edu,IP:192.168.0.223"))

- name: Install logstash patterns
  copy: src=logstash/patterns/{{ item }} dest=/etc/logstash/patterns/{{ item }}
  with_items:
  - ntp.grok
  - postfix.grok
  - selinux.grok
  notify: restart logstash
  tags:
  - logstash

- name: Install logstash.service
  copy: src=logstash/logstash.service dest=/etc/systemd/system/logstash.service
  tags:
  - services
  - logstash

- name: Enable and start logstash
  service: name=logstash enabled=yes state=started
  tags:
  - services
  - logstash
