---
- name: Install etcd from official binary release
  get_url: url="https://github.com/coreos/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
           dest="/root/etcd-v{{ etcd_version }}-linux-amd64.tar.gz" mode=0755
           checksum="{{ etcd_checksum }}"
  when: ansible_pkg_mgr == "apt"
  tags:
  - packages
  - web

- name: Untar etcd
  unarchive: src="/root/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
             dest=/root/ copy=no
  when: ansible_pkg_mgr == "apt"
  tags:
  - packages
  - web

- name: Install etcd and etcdctl
  copy: src="/root/etcd-v{{ etcd_version }}-linux-amd64/{{ item }}"
        dest=/usr/local/bin/{{ item }} remote_src=yes mode=0755
  with_items:
  - etcd
  - etcdctl
  when: ansible_pkg_mgr == "apt"
  tags:
  - packages
  - web
 
- name: Create a etcd group
  group: name=etcd system=yes state=present
  when: ansible_pkg_mgr == "apt"
  tags:
  - packages
  - web

- name: Create a etcd user
  user: name=etcd group=etcd home=/var/lib/etcd shell=/sbin/nologin
        system=yes state=present
  when: ansible_pkg_mgr == "apt"
  tags:
  - packages
  - web

- name: Create /etc/systemd/system/etcd.service
  template: src=etcd.service.j2 dest=/etc/systemd/system/etcd.service
  tags:
  - packages
  - web

- name: Start and enable etcd
  service: name=etcd state=started enabled=yes
  tags:
  - services
  - web

#- name: Install etcd (apt)
#  apt: name=etcd state=latest
#  when: ansible_pkg_mgr == "apt"
#  tags:
#  - packages
#  - web

- name: Install etcd (yum)
  yum: name=etcd state=latest
  when: ansible_pkg_mgr == "yum"
  tags:
  - packages
  - web

- name: Start and enable etcd
  service: name=etcd state=started enabled=yes
  tags:
  - services
  - web

- name: Install nginx_config_etcd.py
  copy: src=nginx_config_etcd.py dest=/usr/local/bin/nginx_config_etcd.py
        mode=0755
  tags:
  - web

- name: Install nginx-config-etcd.service
  copy: src=nginx-config-etcd.service
        dest=/etc/systemd/system/nginx-config-etcd.service
  tags:
  - web

- name: Start and enable nginx-config-etcd
  service: name=nginx-config-etcd state=started enabled=yes
  tags:
  - services
  - web
