---
- name: Create /mnt/automation
  file: dest=/mnt/automation state=directory

- name: Set up /mnt/automation mount
  mount: name=/mnt/automation fstype=nfs
         src=192.168.0.55:/mnt/mckillican/automation state=mounted

- include: packages.yml
- include: johnnysix.yml
