---
- name: Apt update
  apt: update_cache=yes upgrade=yes
  tags:
  - apt
  - packages

- name: Install automation packages
  apt: name={{ item }} state=latest
  with_items:
  - alsa-utils
  - liquidsoap
  - liquidsoap-mode
  - liquidsoap-plugin-all
  - python3
  - socat
  tags:
  - packages
