- hosts: centos
  user: root
  handlers:
  - include: handlers/mail.yml
  - include: handlers/ssh.yml
  roles:
  - common
  - centos-common

- hosts: stream
  user: root
  roles:
  - stream

- hosts: kvm
  user: root
  roles:
  - kvm

- hosts: file
  user: root
  roles:
  - file

# TODO: Write the ldap role
- hosts: ldap
  user: root
  roles:
  - ldap

# TODO: Write the mail role
- hosts: mail
  user: root
  roles:
  - mail

# TODO: Write internal-site role
- hosts: internal-site
  user: root
  roles:
  - internal-site

# TODO: Wtire external-site role
- hosts: external-site
  user: root
  roles:
  - external-site
