- hosts: centos
  become: yes
  handlers:
  - include: handlers/mail.yml
  - include: handlers/ssh.yml
  roles:
  - centos-common
  - common
  - freeipa-client
  - log-forwarder

- hosts: stream
  become: yes
  roles:
  - stream

- hosts: kvm
  become: yes
  roles:
  - kvm

- hosts: file
  become: yes
  roles:
  - file

- hosts: fileserver
  become: yes
  roles:
  - freeipa-client
  - log-forwarder

- hosts: ldap
  become: yes
  roles:
  - ldap

# TODO: Write the mail role
- hosts: mail
  become: yes
  roles:
  - mail

# TODO: Write internal-site role
- hosts: internal-webserver
  become: yes
  roles:
  - webserver
  - certbot
  - db
  - media-wiki
  - radiothon
  - music-db

# TODO: Write external-site role
- hosts: external-webserver
  become: yes
  roles:
  - webserver
  - certbot
  - db
  - object-store
  - website

- hosts: debian
  become: yes
  handlers:
  - include: handlers/mail.yml
  - include: handlers/ssh.yml
  roles:
  - debian-common
  - common
  - ldap-client
  - log-forwarder

- hosts: logstash
  become: yes
  vars:
    nginx_ocsp_stapling: false
  roles:
  - logstash

- hosts: automation
  become: yes
  roles:
  - automation

#- hosts: aircheck
#  become: yes
#  roles:
#  - aircheck

- hosts: nginx
  become: yes
  roles:
  - nginx
  - certbot

- hosts: rds
  become: yes
  roles:
  - rds

- hosts: macpros
  become: yes
  roles:
  - macpros
