- hosts: centos
  user: root
  handlers:
  - include: handlers/mail.yml
  - include: handlers/ssh.yml
  roles:
  - common
  - centos-common

# TODO: Write web role
# TODO: Write db role
- hosts: webservers
  user: root
  roles:
  - web
  - db

#- hosts: stream
#  user: root
#  roles:
#  - stream

- hosts: kvm
  user: root
  roles:
  - kvm

# TODO: Write the file role
- hosts: file
  user: root
  roles:
  - file

# TODO: Write the ldap role
- hosts: ldap
  user: root
  roles:
  - ldap

# TODO: Write the mail role
- hosts: mail
  user: root
  roles:
  - mail

# TODO: Write internal role
- hosts: internal
  user: root
  roles:
  - internal

# TODO: Wtire external role
- hosts: external
  user: root
  roles:
  - external
