- hosts: centos
#  become: yes
#  become: yes
#  become_user: root
#  become_method: sudo
  handlers:
  - include: handlers/mail.yml
  - include: handlers/ssh.yml
  roles:
  - centos-common
  - common

- hosts: stream
  become: yes
  roles:
  - stream

- hosts: kvm
  become: yes
  roles:
  - kvm

- hosts: file
  become: yes
  roles:
  - file

- hosts: ldap
  become: yes
  roles:
  - ldap

# TODO: Write the mail role
- hosts: mail
  become: yes
  roles:
  - mail

# TODO: Write internal-site role
- hosts: internal-webserver
  become: yes
  roles:
  - webserver
  - db
  - media-wiki
  - radiothon
  - music-db

# TODO: Write external-site role
- hosts: external-webserver
  become: yes
  roles:
  - webserver
  - db
  - object-store
  - website

- hosts: workstations
  #user: ladmin
  roles:
  - common
  - ubuntu-common
  - ubuntu-desktop
  - role: jnv.unattended-upgrades
    unattended_origins_patterns:
    - 'origin=Ubuntu,archive=${distro_codename}-security'
    - 'o=Ubuntu,a=${distro_codename}-updates'
    #unattended_package_blacklist: [cowsay, vim]
    unattended_mail: 'root@wuvt.vt.edu'
  become: yes

- hosts: debian
 # become: yes
  handlers:
  - include: handlers/mail.yml
  - include: handlers/ssh.yml
  roles:
  - common
  - debian-common

- hosts: logstash
  become: yes
  vars:
    nginx_ocsp_stapling: false
  roles:
  - logstash
