- hosts: centos
  user: root
  handlers:
  - include: handlers/mail.yml
  - include: handlers/ssh.yml
  roles:
  - common
  - centos-common

- hosts: stream
  user: root
  roles:
  - stream

- hosts: kvm
  user: root
  roles:
  - kvm

- hosts: file
  user: root
  roles:
  - file

- hosts: ldap
  user: root
  roles:
  - ldap

# TODO: Write the mail role
- hosts: mail
  user: root
  roles:
  - mail

# TODO: Write internal-site role
- hosts: internal-webserver
  user: root
  roles:
  - webserver
  - db
  - media-wiki
  - radiothon
  - music-db

# TODO: Write external-site role
- hosts: external-webserver
  user: root
  roles:
  - webserver
  - db
  - object-store
  - website

- hosts: workstations
  #user: ladmin
  roles:
  - common
  - ubuntu-common
  sudo: yes
