- hosts: rhel6
  user: root
  vars_files:
  - vars/default.yml
  - vars/private.yml
  tasks:
  - include: tasks/rhel_network.yml
  - include: tasks/rhel_sudo.yml
  - include: tasks/rhel_hostname.yml
  - include: tasks/rhel_yum.yml
  - include: tasks/create_user.yml user=matt group=wheel uid=1000
  - include: tasks/rhel_mail.yml
  - include: tasks/rhel_noselinux.yml
  - include: tasks/rhel_ntp.yml
  - include: tasks/rhel_smart.yml
  - include: tasks/rhel_packages.yml
  handlers:
  - include: handlers/mail.yml
  - include: handlers/ntp.yml
  - include: handlers/ssh.yml
