---
- name: Install desktop software
  apt: name={{ item }} state=latest
  with_items:
  - libreoffice
  - mpv
  - vlc
  - texmaker
  - tex4ht
  - cheese
  - k3b
  - k3b-data
  - libk3b6-extracodecs
  - thunderbird
  - redshift
  tags:
  - packages

- name: Ubuntu 14.04-specific software
  when: ansible_distribution_version == "14.04"
  apt: name={{ item }} state=latest
  with_items:
  - morituri

- name: LightDM config file to disable guest login
  copy: src=50-no-guest.conf dest=/usr/share/lightdm/lightdm.conf.d/50-no-guest.conf

- name: Restart lightDM
  service: name=lightdm state=restarted
