---
- name: Stop and disable nscd
  service: name=nscd state=stopped enabled=no
  ignore_errors: yes
  when: ansible_distribution_version == "14.04" or ansible_os_family == "RedHat"

- include: centos.yml
  when: ansible_os_family == "RedHat"

- include: debian.yml
  when: ansible_os_family == "Debian"

- name: Add the sudoers group to allowed sudoers
  copy: src=sudoers.d/01_sudoers dest=/etc/sudoers.d/01_sudoers

- name: Make sure openldap and sssd configuration directories exist
  file: path={{ item }} state=directory
  with_items:
  - /etc/openldap
  - /etc/openldap/cacerts
  - /etc/sssd

- name: Install LDAP TLS certificate
  copy: src=ldap.pem dest={{ item }}/ldap.pem
  with_items:
  - /etc/sssd
  - /etc/openldap/cacerts

- name: Install /etc/sssd/sssd.conf
  copy: src=sssd.conf dest=/etc/sssd/sssd.conf owner=root group=root mode=0600
  notify: Restart sssd

- name: Start and enable sssd
  service: name=sssd state=started enabled=yes
  tags:
  - services
