- name: Copy compilation scripts
  copy: src=compile_faac.sh dest=/tmp/compile_faac.sh owner=root group=root mode=0755
  tags:
  - stream
  - compiling
- name: Copy compilation scripts
  copy: src=compile_darkice.sh dest=/tmp/compile_darkice.sh owner=root group=root mode=0755
  tags:
  - stream
  - compiling
- name: Compile libfaac
  command: /tmp/compile_faac.sh
  ignore_errors: yes
  tags:
  - stream
  - compiling
- name: Compile darkice
  command: /tmp/compile_darkice.sh
  ignore_errors: yes
  tags:
  - stream
  - compiling

- name: Add local libraries to ld.so.conf
  template: src=local.conf.j2 dest=/etc/ld.so.conf.d/local.conf mode=0644
  tags:
  - stream
  - compiling
- name: Update local libraries
  command: ldconfig
  tags:
  - stream
  - compiling

- name: Install darkice init script
  copy: src=darkice-init.sh dest=/etc/init.d/darkice owner=root group=root mode=0755
  tags:
  - stream
  - compiling

