- name: Install audio streaming packages and libraries
  yum: name=$item state=latest
  with_items:
  - icecast
  - alsa-utils
  - alsa-lib
  - alsa-lib-devel
  - alsa-utils
  - libvorbis
  - libvorbis-devel
  - libvorbis-devel-docs
  - vorbis-tools
  - libogg
  - libogg-devel
  - libogg-devel-docs
  - liboggz
  - liboggz-devel
  - liboggz-doc
  - opus-devel
  - opus
  - libmp3lame0
  tags:
  - packages
  - stream
- name: Install icecast.xml
  template: src=icecast.xml.j2 dest=/etc/icecast.xml mode=0660
  tags:
  - stream


- name: Copy compilation scripts
  copy: src=compile_faac.sh dest=/tmp/compile_faac.sh owner=root group=root mode=0755
  tags:
  - stream
  - compiling
- name: Copy compilation scripts
  copy: src=compile_darkice.sh dest=/tmp/compile_darkice.sh owner=root group=root mode=0755
  tags:
  - stream
  - compiling
- name: Compile libfaac
  command: /tmp/compile_faac.sh
  ignore_errors: yes
  tags:
  - stream
  - compiling
- name: Compile darkice
  command: /tmp/compile_darkice.sh
  ignore_errors: yes
  tags:
  - stream
  - compiling


- name: Add local libraries to ld.so.conf
  template: src=local.conf.j2 dest=/etc/ld.so.conf.d/local.conf mode=0644
  tags:
  - stream
  - compiling
- name: Update local libraries
  command: ldconfig
  tags:
  - stream
  - compiling

- name: Install darkice init script
  copy: src=darkice-init.sh dest=/etc/init.d/darkice owner=root group=root mode=0755
  tags:
  - stream
  - compiling


- name: Install darkice.cfg
  template: src=darkice.cfg.j2 dest=/etc/darkice.cfg mode=0644
  tags: 
  - stream
- name: Stop icecast service
  service: name=icecast state=stopped
  tags:
  - stream
- name: Enable icecast service
  service: name=icecast enabled=yes
  tags:
  - stream
- name: Start icecast service
  service: name=icecast state=started
  tags:
  - stream
- name: Stop darkice service
  service: name=darkice state=stopped
  tags:
  - stream
- name: Enable darkice service
  service: name=darkice enabled=yes
  tags:
  - stream
- name: Start darkice service
  service: name=darkice state=started
  tags:
  - stream

# TODO add /usr/local/{bin,sbin} to paths

