- name: Install Cups packages
  yum: name={{ item }} state=latest
  with_items:
    - cups
    - hplip
    - hplip-common
    - hplip-libs
    - ghostscript
    - ghostscript-fonts
  tags:
  - packages

- name: Place cupsd.conf file
  template: src=cupsd.conf dest=/etc/cups/cupsd.conf mode=0644
  tags: configure

- name: Enable Cups services
  service: name=cups state=restarted enabled=yes
  tags: cups

