---
- include: ldap-client.yml
- include: nfs.yml
- include: packages.yml
  when: ansible_distribution_version == "14.04"

- include: packagesnew.yml
  wehn: ansible_distribution_version == "16.04"


