- name: Install NFS client utilities
  apt: name={{ item }} state=latest
  with_items:
  - nfs-common
  tags:
  - packages

- name: Install /etc/idmapd.conf
  copy: src=idmapd.conf dest=/etc/idmapd.conf
