- name: Install NFS client utilities
  apt: name={{ item }} state=latest
  with_items:
  - nfs-common
  tags:
  - packages

####this really shouldn't need to be done. if it does, of course uncomment it
#- name: create dirs for ladmin
#  file: path=/usr/local/home recurse=yes state=directory owner=root
#  tags:
#  - local
#- name: Create ladmin
#  user: name=ladmin groups=root,sudo home=/usr/local/home/ladmin
#  tags:
#  - local 

- name: Set local home dir
  file: path=/usr/local/home/ladmin recurse=yes state=directory owner=ladmin
  tags: 
  - local

#- name: Move user's home dir
#  user: name=ladmin home=/usr/local/home/ladmin
#  tags:
#  - local

- name: change /etc/fstab
  mount: fstype=nfs name=/home src=192.168.0.55:/mnt/mckillican/home state=mounted
