- name: Install NFS client utilities
  apt: name={{ item }} state=latest
  with_items:
  - nfs-common
  tags:
  - packages

- name: Install /etc/idmapd.conf
  copy: src=idmapd.conf dest=/etc/idmapd.conf

- name: Unmount /home from NFS
  mount: fstype=nfs name=/home src=192.168.0.55:/mnt/mckillican/home state=unmounted
