---
- name: Install sources.list
  copy: src=sources.list dest=/etc/apt/sources.list mode=0664 owner=root group=root
  tags:
  - apt
  - dropbox


- name: Install common packages
  apt: name={{ item }} state=latest
  with_items:
  - git
  - htop
  - vim
  - man
  - nmap
  - ncdu
  - rsync
  - screen
  - tmux
  - wget
  - zsh
  - cowsay
  - ntp
  - ranger
  - aptitude
  - python-apt
  - pwgen
  tags:
  - packages

- name: Install packages for development
  apt: name={{ item }} state=latest
  with_items:
  - gcc
  - ruby
  - ansible
  - sshpass
  tags:
  - packages

- name: Install ansible config
  copy: src=ansible.cfg dest=/etc/ansible/ansible.cfg mode=0644 owner=root group=root
  tags:
  - ansible

- name: Install desktop software
  apt: name={{ item }} state=latest
  with_items:
  - libreoffice
  - mpv
  - vlc
  - texmaker
  - cheese
  - morituri
  - k3b
  - k3b-data
  - libk3b6-extracodecs
  - thunderbird
  tags:
  - packages

- name: Force install dropbox
  apt: name={{ item }} state=latest force=yes
  with_items:
  - dropbox
  tags:
  - packages
  - dropbox

- name: Apt update
  apt: update_cache=yes upgrade=yes
  tags:
  - apt
  - packages
