---
# tasks file for mysql
- name: set mysql_server_id based on ip address
  set_fact: mysql_server_id={{ ansible_eth0.ipv4.address|regex_replace("^.{0,3}|[.]") }}
  when: mysql_server_id is not defined

- name: install packages
  yum: pkg={{ item }} state=installed
  with_items: mysql_packages
  register: mysql_install

- name: configure the service
  template: src=my.cnf.j2 dest=/etc/my.cnf owner=root group=root mode=0644
  notify: restart mysql

- name: ensure mysql is started
  service: name={{ mysql_service_name }} state=started enabled=yes

- name: configure root user password
  mysql_user: name=root password={{ mysql_root_password }} state=present priv=*.*:ALL,GRANT

- name: configure the new password
  template: src=client_my.cnf.j2 dest=~/.my.cnf owner=root group=root mode=0600
