---
- name: Install fail2ban (APT)
  apt: name=fail2ban state=present
  when: ansible_pkg_mgr == "apt"

- name: Install fail2ban (yum)
  yum: name=fail2ban state=present
  when: ansible_pkg_mgr == "yum"

- name: Install jail.local
  copy: src=jail.local dest=/etc/fail2ban/jail.local
  notify: Restart fail2ban
