- name: Configure system hostname
  lineinfile: dest=/etc/sysconfig/network regexp=^HOSTNAME= line=HOSTNAME=$hostname state=present
- name: Add IPv4 hostname entries to /etc/hosts
  lineinfile: dest=/etc/hosts regexp=^127\.0\.0\.1 line="127.0.0.1   {{ hostname }} localhost localhost.localdomain localhost4 localhost4.localdomain4" state=present
- name: Add IPv6 hostname entries to /etc/hosts
  lineinfile: dest=/etc/hosts regexp=^::1 line="::1         {{ hostname }} localhost localhost.localdomain localhost6 localhost6.localdomain6" state=present
- name: Set system hostname immediately
  command: hostname {{ hostname }}
