---
- name: Configure system hostname
  hostname:
    name: "{{ hostname }}"
  tags:
  - common

- name: Add IPv4 hostname entries to /etc/hosts
  lineinfile: dest=/etc/hosts regexp=^127\.0\.0\.1 line="127.0.0.1   {{ hostname }} localhost localhost.localdomain localhost4 localhost4.localdomain4" state=present
  tags:
  - common

- name: Add IPv6 hostname entries to /etc/hosts
  lineinfile: dest=/etc/hosts regexp=^::1 line="::1         {{ hostname }} localhost localhost.localdomain localhost6 localhost6.localdomain6" state=present
  tags:
  - common
