---
- name: Stop iptables service
  service: name=iptables state=stopped
  tags:
  - services
  - common

- name: Disable iptables service
  service: name=iptables enabled=no
  tags:
  - services
  - common

- name: Stop ip6tables service
  service: name=ip6tables state=stopped
  tags:
  - services
  - common

- name: Disable ip6tables service
  service: name=ip6tables enabled=no
  tags:
  - services
  - common
