---
- name: Copy sshd config (RHEL7)
  copy: src=sshd_config_rhel7 dest=/etc/ssh/sshd_config mode=0600
  when: ansible_distribution_version.split(".")[0] == "7"
  notify: Restart sshd

- name: Copy sshd config (RHEL6)
  copy: src=sshd_config_rhel6 dest=/etc/ssh/sshd_config mode=0600
  when: ansible_distribution_version.split(".")[0] == "6"
  notify: Restart sshd

- name: Enable and start sshd
  service: name=sshd state=started enabled=yes
