---
- include: noselinux.yml
- include: packages.yml
- include: hostname.yml
- include: sudo.yml
#- include: yum.yml
- include: mail.yml
#- include: iptables.yml
- include: ldap-client.yml
#- include: nfs-client.yml
