- include: hostname.yml
- include: packages.yml
- include: sudo.yml
- include: yum.yml
- include: mail.yml
- include: noselinux.yml
- include: ntp.yml
- include: iptables.yml
- include: ldap-client.yml
- include: nfs-client.yml
