---
- include: noselinux.yml
- include: packages.yml

- include: hostname.yml
  when: hostname is defined

- include: yum.yml
- include: mail.yml

- include: iptables.yml
  when: ansible_distribution_version.split(".")[0] == "6"
