- name: Install NFS packages
  yum: name={{ item }} state=latest
  with_items:
  - nfs-utils
  - nfs-utils-lib
  - nfs-utils-lib-devel
  - nfs4-acl-tools
  when: ansible_distribution_version.split(".")[0] == "6"
  tags:
  - packages

- name: Enable and start nfs-client.target
  service: name=nfs-client.target state=started enabled=yes
  when: ansible_distribution_version.split(".")[0] == "7"
  tags:
  - nfs

- name: Mount /home from NFS
  mount: fstype=nfs name=/home src=192.168.0.55:/mnt/mckillican/home state=mounted
