- name: Add NFS home directory mount to fstab
  lineinfile: >
    dest=/etc/fstab regexp='' insertafter=EOF 
    line="192.168.0.55:/mnt/mckillican/home       /home       nfs     rw,intr,noacl,nocto 0 0"
- name: Remount everything in fstab to mount new home directories
  command: mount -a
