---
- name: Download EPEL package for CentOS 6
  get_url: url=https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm dest=/tmp/epel-release-6.8.noarch.rpm mode=0400
  when: ansible_distribution_version.split(".")[0] == "6"
#  when: ansible_distribution_major_version == "6"


- name: Enable EPEL - CentOS 6
  command: rpm -Uvh /tmp/epel-release-6.8.noarch.rpm creates=/etc/yum.repos.d/epel.repo
#  when: ansible_distribution_major_version == "6"
  when: ansible_distribution_version.split(".")[0] == "6"

- name: Enable EPEL - CentOS 7
  yum: pkg=epel-release state=latest
  when: ansible_distribution_version.split(".")[0] == "7"
#  when: ansible_distribution_major_version == "7"

- name: Install common packages
  yum: name={{ item }} state=latest
  with_items:
  - yum-cron
  - smartmontools
  - emacs-nox
  - elinks
  - git
  - git-svn
  - htop
  - lsof
  - lynx
  - man
  - mosh
  - mtr
  - nmap
  - ncdu
  - vim
  - rsync
  - screen
  - subversion
  - tmux
  - wget
  - zsh
  - pciutils
  - bind-utils
  - bash-completion
  - ntp
  - ntpdate
  - ntp-doc
  - weechat
  - weechat-devel
  tags:
  - packages

- name: Install packages for development
  yum: name={{ item }} state=latest
  with_items:
  - gcc
  - make
  - openmpi
  - openmpi-devel
  - ruby
  - autoconf
  - automake
  - bison
  - byacc
  - cscope
  - ctags
  - diffstat
  - doxygen
  - elfutils
  - flex 
  - gcc-c++
  - indent
  - intltool
  - libtool
  - patch
  - patchutils
  - rcs
  - redhat-rpm-config
  - rpm-build
  - swig
  - systemtap
  - unzip
  - zip
  - libselinux-python
  tags:
  - packages
