---
- name: Change who recieves the daily yum update emails
  lineinfile: dest=/etc/sysconfig/yum-cron regexp=^MAILTO= line="MAILTO=root@wuvt.vt.edu" state=present
  when: ansible_distribution_version.split(".")[0] == "6"
  tags:
  - common

# XXX: apparently yum-cron conflicts with yum? disabled until we figure this out
#- name: Enable and start yum-cron service
#  service: name=yum-cron state=started enabled=yes
#  tags:
#  - services
#  - common
