filebeat:
  prospectors:
    -
      paths:
        - "/var/log/audit/*.log"
      document_type: selinux
    -
      paths:
        - "/var/log/cron"
      document_type: cron
    -
      paths:
        - "/var/log/auth.log"
        - "/var/log/maillog"
        - "/var/log/messages"
        - "/var/log/secure"
      document_type: syslog
    -
      paths:
        - "/var/log/yum.log"
      document_type: yum
output:
  logstash:
    hosts: ["192.168.0.223:5043"]
    tls:
      certificate_authorities: ["/etc/filebeat/logstash.pem"]
    index: filebeat
