filebeat:
  prospectors:
    -
      paths:
        - "/var/log/audit/*.log"
        - "/var/log/nginx/*.log"
        - "/var/log/*.log"
        - "/var/log/cron"
        - "/var/log/maillog"
        - "/var/log/messages"
        - "/var/log/secure"

      input_type: log
output:
  logstash:
    hosts: ["192.168.0.223:5043"]
    index: filebeat
