---
- name: Install celery-wuvt config
  copy: src=celery-wuvt dest=/etc/sysconfig/celery-wuvt
  tags:
  - website
  - services

- name: Install celery-wuvt.service
  copy: src=celery-wuvt.service dest=/etc/systemd/system/celery-wuvt.service
  tags:
  - website
  - services

- name: Enable celery-wuvt.service
  service: name=celery-wuvt enabled=yes
  tags:
  - website
  - services

- name: Start celery-wuvt.service
  service: name=celery-wuvt state=started
  tags:
  - website
  - services
