---
- name: Install uWSGI dependencioes
  yum: name={{ item }} state=latest
  with_items:
  - libuuid-devel
  - libxml2-devel
  - libyaml-devel
  - pcre-devel
  - python-devel
  tags:
  - website
  - packages

- name: download uWSGI
  get_url: >
    url=https://github.com/unbit/uwsgi/archive/{{ uwsgi_version }}.tar.gz
    dest=/root/uwsgi-{{ uwsgi_version }}.tar.gz checksum={{ uwsgi_checksum }}

- name: extract uWSGI
  command: /usr/bin/tar -axvf uwsgi-{{ uwsgi_version }}.tar.gz chdir=/root/

- name: copy uWSGI build configuration
  copy: src=centos.ini
        dest=/root/uwsgi-{{ uwsgi_version }}/buildconf/centos.ini

- name: copy build_uwsgi.sh
  template: src=build_uwsgi.sh.j2 dest=/root/build_uwsgi.sh mode=0755

- name: build uWSGI and plugins
  shell: build_uwsgi.sh chdir=/root/

- name: Install uwsgi-wuvt.service
  copy: src=uwsgi-wuvt.service dest=/etc/systemd/system/uwsgi-wuvt.service
  tags:
  - website
  - services

- name: Create uwsgi run directory
  file: path=/run/uwsgi state=directory owner=nginx

- name: Enable uwsgi-wuvt.service
  service: name=uwsgi-wuvt enabled=yes
  tags:
  - website
  - services

- name: Start uwsgi-wuvt.service
  service: name=uwsgi-wuvt state=started
  tags:
  - website
  - services
