---
- name: Install ntp.conf
  template: src=templates/ntp.conf.j2 dest=/etc/ntp.conf mode=0644
  notify: Restart ntpd
  tags:
  - common

- name: Enable and start ntpd service
  service: name=ntpd enabled=yes state=started
  tags:
  - services
  - common
