---
- name: Install tor (pacman)
  pacman: name=tor state=present
  when: ansible_pkg_mgr == "pacman"
  tags: packages

- name: Install tor (yum)
  yum: name=tor state=present
  when: ansible_pkg_mgr == "yum"
  tags: packages

#- name: Install torrc
#  template: src=torrc.j2 dest=/etc/tor/torrc
#  notify: Reload tor

- name: Enable and start tor
  service: name=tor state=started enabled=yes
