---
- name: Install etcd
  yum: name=etcd state=present

- name: Install etcd.conf
  template: src=etcd.conf.j2 dest=/etc/etcd/etcd.conf
  notify: Restart etcd

- name: Start and enable etcd
  service: name=etcd state=started enabled=yes
