---
- include: centos.yml
  when: ansible_os_family == "RedHat"

#- include: debian.yml
#  when: ansible_os_family == "Debian"

- name: Install filebeat config
  copy: src=filebeat.yml dest=/etc/filebeat/filebeat.yml
  tags:
  - log-forwarder

- name: Enable and start filebeat
  service: name=filebeat enabled=yes state=started
  tags:
  - services
  - log-forwarder
