---
- name: Install redis
  yum: pkg=redis state=latest
  tags:
  - packages
  - object-store

- name: Enable redis service
  service: name=redis enabled=yes
  tags:
  - services
  - object-store

- name: Start redis service
  service: name=redis state=started
  tags:
  - services
  - object-store
